name: Publicação Acadêmico

on:
  workflow_dispatch:
  
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: Checkout
      uses: actions/checkout@v2
    - name: Testando
      run: echo "Iniciando publicação do projeto acadêmico pluft plaft zummmmmm"
